### ISSUE TITLE
Create jamulus organisation account 

### ISSUE THREAD

**Issue by ann0see** [gilgongo/jamulushome#2]
Since the preferred site would be available on jamulus.github.io we have to create a new user account and/or Organisation on GitHub. 

@corrados should probably create this because he’s the lead developer. I‘m not sure if corrados/jamulus should also be added to the jamulus organisation (e.g. under jamulus/jamulus or jamulus/source) or if it should be left on corrados private account (the links will not be broken if we change the owner, I think). 

At the moment the account @jamulus already exists. I don’t know who owns this account. Maybe someone of the jamulus project?

**Comment by corrados** [comment]
> Maybe someone of the jamulus project?

It's not me.

**Comment by ann0see** [comment]
That's not good. I hope, the owner of this account sees this thread. Can we somehow message him or get the account name @Jamulus I'm not sure if we should notify GitHub about this.

**Comment by Jamulus** [comment]
Hi its me Jamulus. This is my personal github, and frankly I'd like to keep it, thanks.

**Comment by ann0see** [comment]
Hi @Jamulus thank you for your response! While I do understand that you would like to keep your account, please also remember that Jamulus is the name of a project by @corrados which enables online jamming and is currently setting up a new website. It would be great if we could use the subdomain jamulus.github.io. Unfortunately this would only be possible if you created another GitHub account with another name e.g. jamus, jamulus1, jamuus etc.

**Comment by chrisrimple** [comment]
@Jamulus I certainly understand your desire to keep the name Jamulus for your personal github.  Jamulus (the project) has become very popular and has enabled musicians from around the world to return to rehearsing, and even performing, online while limited by the pandemic.  Perhaps you're a musician yourself, and have used it?  I encourage you to view these links for a sense of what's being done with the Jamulus project...

https://worldjam.vip/homepage.php
https://www.youtube.com/c/WorldJam

The project contributors would really appreciate it if you could change your github name, freeing Jamulus up for the project's use.  Thanks!
